## Extension should always be (.properties)
## Key=value pair is present inside properties file

browser = chrome

url = http://www.instagram.com

#************************ Data to be fed *******************************#

userId = life_on_a_bullet

password = Sfit@561


#************************ Element locators *******************************#

user_name = username

pwd_name = password

submit = //button[@type='submit']

